version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: webvirtcloud-frontend
    hostname: frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - global.env
      - custom.env
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: webvirtcloud-backend
    hostname: backend
    ports:
      - 127.0.0.1:8000:8000
    command: gunicorn webvirtcloud.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - global.env
      - custom.env
    depends_on:
      - mariadb
  novnc:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: webvirtcloud-novnc
    hostname: novnc
    ports:
      - 127.0.0.1:6080:6080
    command: python3 manage.py novncd --verbose
    env_file:
      - global.env
      - custom.env
    depends_on:
      - mariadb
  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: webvirtcloud-worker
    hostname: worker
    command: celery -A webvirtcloud worker -l info
    env_file:
      - global.env
      - custom.env
    depends_on:
      - mariadb
      - rabbitmq
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: webvirtcloud-scheduler
    hostname: scheduler
    command: celery -A webvirtcloud beat -l info
    env_file:
      - global.env
      - custom.env
    depends_on:
      - worker
      - mariadb
      - rabbitmq
  mariadb:
    image: mariadb:10.6.10
    container_name: webvirtcloud-mariadb
    hostname: mariadb
    volumes:
      - ./.mysql:/var/lib/mysql
    env_file:
      - global.env
      - custom.env
  rabbitmq:
    image: rabbitmq:3.10.13
    container_name: webvirtcloud-rabbitmq
    hostname: rabbitmq
    env_file:
      - global.env
      - custom.env