version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    hostname: frontend
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      API_DOMAIN: "api.webvirt.cloud"
      CLIENT_DOMAIN: "client.webvirt.cloud"
      MANAGE_DOMAIN: "manage.webvirt.cloud"
      CONSOLE_DOMAIN: "console.webvirt.cloud"
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    hostname: backend
    ports:
      - 8000:8000
    command: gunicorn webvirtcloud.wsgi:application --bind 0.0.0.0:8000
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.production
      CELERY_BROKER_URL: "amqp://django:django@rabbitmq:5672/webvirtcloud"
    depends_on:
      - mariadb
  novnc:
    build:
      context: .
      dockerfile: Dockerfile.backend
    hostname: novnc
    ports:
      - 6080:6080
    command: python3 manage.py novncd --verbose
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.production
    depends_on:
      - mariadb
  beat:
    build:
      context: .
      dockerfile: Dockerfile.backend
    hostname: beat
    command: celery -A webvirtcloud beat -l info
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.production
      CELERY_BROKER_URL: "amqp://django:django@rabbitmq:5672/webvirtcloud"
    depends_on:
      - rabbitmq
      - mariadb
  worker:
    build:
      context: .
      dockerfile: Dockerfile.backend
    hostname: worker
    command: celery -A webvirtcloud worker -l info
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.production
      CELERY_BROKER_URL: "amqp://django:django@rabbitmq:5672/webvirtcloud"
    depends_on:
      - rabbitmq
      - mariadb
  mariadb:
    image: mariadb:10.6.10
    hostname: mariadb
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: webvirtcloud
      MARIADB_USER: django
      MARIADB_PASSWORD: django
      MARIADB_ROOT_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3.10.13
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: django
      RABBITMQ_DEFAULT_PASS: django
      RABBITMQ_DEFAULT_VHOST: /webvirtcloud